### ISSUE TITLE
Does this allow for schema evolution

### ISSUE THREAD

**Issue by manyasi06** [domnikl/schema-registry-gitops#79]
Question is possible to do schema evolution with this tool:

```
compatibility: BACKWARD

subjects:
  
  - name: sample-value
    file: sample1.avsc
    compatibility: BACKWARD

  - name: sample-value
    file: sample1_v2.avsc
    compatibility: BACKWARD
```

If curl the schema registry I would get the following:
```
curl http://localhost:8081/subjects/sample-value/versions
[1,2]
```

**Comment by domnikl** [comment]
Hello @manyasi06,
schema-registry-gitops helps you to do schema evolution in that it checks if the evolution is possible before applying it and is perfectly suited to go into you CI pipeline to check a PR before that code and corresponding schema changes are being deployed into production. It does not work with multiple versions though and always checks only the latest version when using `BACKWARD`, if you want to check for earlier versions also you should use `BACKWARD_TRANSITIVE`. More information about that can be found in the documentation of `schema-registry`: https://docs.confluent.io/platform/current/schema-registry/avro.html#compatibility-types

If you want to check for another **major** version that will break backwards-compatibility, you need to also  adjust the `name` accordingly. This way, they aren't related to each other and can involve independently. Config would then look like this:

```yaml
compatibility: BACKWARD

subjects:
  
  - name: sample-value
    file: sample1.avsc
    compatibility: BACKWARD

  - name: sample-value-v2
    file: sample1_v2.avsc
    compatibility: BACKWARD
```
