### ISSUE TITLE
support schema references

### ISSUE THREAD

**Issue by domnikl** [domnikl/schema-registry-gitops#8]
All subcommands should support schema references.

YAML schema should look like this:

```yaml
compatibility: FULL_TRANSITIVE
subjects:
  - name: subject1-value
    file: subject1-value.avsc
  - name: subject2-value
    references:
      - subject1-value
    file: my-actual-schema.avsc
```

References are only supported for server versions >=5.5, see https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#referenced-schemas
